### ISSUE TITLE
Error on getting the list of simulators

### ISSUE THREAD

**Issue by barzhomi** [wanderwaltz/xcsim#2]
In addition to warning from #1 command `xcsim --list` fails with the next

```
/Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbAppBundles.rb:47:in `open': No such file or directory @ dir_initialize - /Users/barzhomi/Library/Developer/CoreSimulator/Devices/D8648A66-6C13-436E-BDCF-EC774A60745F/data/Containers/Data/Application (Errno::ENOENT)
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbAppBundles.rb:47:in `entries'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbAppBundles.rb:47:in `findBundleDataPath'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbAppBundles.rb:112:in `block in parseInstalledBundles'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbAppBundles.rb:109:in `map'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbAppBundles.rb:109:in `parseInstalledBundles'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbList.rb:92:in `block (2 levels) in allDevices'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbList.rb:91:in `map'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbList.rb:91:in `block in allDevices'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbList.rb:90:in `map'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbList.rb:90:in `allDevices'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbList.rb:64:in `withPattern'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/xcsim-1.0.0/lib/xcsim/rbXCSim.rb:110:in `xcsim'
    from /Users/barzhomi/.rvm/gems/ruby-2.2.0@global/gems/xcsim-1.0.0/bin/xcsim:207:in `<top (required)>'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/bin/xcsim:23:in `load'
    from /Users/barzhomi/.rvm/rubies/ruby-2.2.0/bin/xcsim:23:in `<main>'
    from /Users/barzhomi/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/barzhomi/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wanderwaltz** [comment]
Thanks! Fixed, will be included in 1.0.1 release.
